---
- name: Set RHEL hostname
  ansible.builtin.hostname:
    name: "{{ vm_name | lower }}"

- name: Reboot host
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
